export const project = [
  "📝 DevResume - Learn HTML & CSS by Building a Resume <br/>",
  "🟥 1. What the Heck is HTML?<br/>",
  "HTML is the backbone of every web page. It uses tags to define the structure and content - just like how your resume has sections.<br/>",
  "🏷️ 2. Tags, Elements & Attributes<br/>",
  "Tags are used to wrap content. Like:<br/>",
  "&lt;h1&gt;John Doe&lt;/h1&gt;<br/>",
  "&lt;p&gt;Frontend Developer&lt;/p&gt;<br/>",
  "Attributes add extra info:<br/>",
  '&lt;a href="mailto: john@example.com"&gt;Email Me&lt;/a&gt;<br/>',
  "🏷️ 3. Headings & Paragraphs<br/>",
  "Use headings (`&lt;h1&gt;` to `&lt;h6&gt;`) for titles, and `&lt;p&gt;` for normal text:<br/>",
  "&lt;h1&gt;John Doe&lt;/h1&gt;<br/>",
  "&lt;p&gt;Frontend Developer&lt;/p&gt;<br/>",
  "📋 4. Lists - Bullet Points = Clarity<br/>",
  "Skills? Use unordered lists:<br/>",
  "&lt;ul&gt;<br/>",
  "  &lt;li&gt;HTML&lt;/li&gt;<br/>",
  "  &lt;li&gt;CSS&lt;/li&gt;<br/>",
  "  &lt;li&gt;JavaScript&lt;/li&gt;<br/>",
  '&lt;/ul&gt;<br/>',
  "🔗 5. Links - Connect Your Web",
  '&lt;a href="https://github.com/yourhandle" target="_blank"&gt;GitHub&lt;/a&gt;<br/>',
  "🧱 6. Layout Tags - Giving Your Page a Skeleton<br/>",
  "&lt;header&gt; ... &lt;/header&gt;<br/>",
  "&lt;main&gt; ... &lt;/main&gt;<br/>",
  "&lt;section&gt; ... &lt;/section&gt;<br/>",
  "&lt;footer&gt; ... &lt;/footer&gt;<br/>",
  "Use these to split your resume into logical blocks.<br/>",
  "🧾 7. Forms & Inputs - Making Your Page Listen<br/>",
  "Add a contact form:<br/>",
  "&lt;form&gt;<br/>",
  '  &lt;input type="text" placeholder="Your Name" /&gt;<br/>',
  '  &lt;input type="email" placeholder="Email" /&gt;<br/>',
  '  &lt;button type="submit"&gt;Send&lt;/button&gt;<br/>',
  "&lt;/form&gt;<br/>",
  "📊 8. Tables - Show Data Like a Pro<br/>",
  "&lt;table&gt;<br/>",
  "  &lt;tr&gt;",
  "    &lt;th&gt;Company&lt;/th&gt;<br/>",
  "    &lt;th&gt;Role&lt;/th&gt;<br/>",
  "  &lt;/tr&gt;<br/>",
  "  &lt;tr&gt;<br/>",
  "    &lt;td&gt;Google&lt;/td&gt;<br/>",
  '    &lt;td&gt;Intern&lt;/td&gt;<br/>',
  "  &lt;/tr&gt;<br/>",
  "&lt;/table&gt;<br/>",
  '🎞️ 9. Multimedia - Add Life to Your Page<br/>',
  '&lt;img src="photo.jpg" alt="Profile Photo" /&gt;<br/>',
  '&lt;video controls&gt;<br/>',
  '  &lt;source src="intro.mp4" type="video/mp4" /&gt;<br/>',
  '&lt;/video&gt;<br/>',
  '✅ 10. HTML Best Practices<br/>',
  ' Use semantic tags (`&lt;main&gt;`, `&lt;section&gt;`, `&lt;article&gt;`)<br/>',
  ' Keep it clean and indented<br/>',
  ' Always include `alt` on images<br/>',
  '🌈 11. What is CSS?<br/>',
  'CSS styles your resume - fonts, colors, spacing, etc.<br/>',
  '🧱 12. The Box Model<br/>',
  'Everything in CSS is a box with:<br/>',
  ' Content<br/>',
  ' Padding<br/>',
  ' Border<br/>',
  ' Margin<br/>',
  'Use `border: 1px solid #ccc;` or `padding: 10px;` to test it.<br/>',
  '🎯 13. id vs class<br/>',
  ' Use `id` for unique styling<br/>',
  ' Use `class` for reusable styling<br/>',
  '&lt;div id="header"&gt;&lt;/div&gt;<br/>',
  '&lt;div class="section"&gt;&lt;/div&gt;<br/>',
  '🧱 14. Display<br/>',
  'Control layout with:<br/>',
  ' `display: block;` (default for divs)<br/>',
  ' `display: inline;`<br/>',
  ' `display: flex;` (for flexbox layouts)<br/>',
  '🎨 15. Colors, Themes & Fonts<br/>',
  'body {<br/>',
  '  color: #fff;<br/>',
  '  background-color: #1e1e2f;<br/>',
  "  font-family: 'Poppins', sans-serif;<br/>",
  '}<br/>',
  'Use custom themes for light/dark mode!<br/>',
  '👉 16. Position + Margin vs Padding + Borders & Shadows<br/>',
  'Understand spacing and alignment:<br/>',
  '.card {<br/>',
  '  margin: 20px;<br/>',
  '  padding: 15px;<br/>',
  '  border: 1px solid #444;<br/>',
  '  box-shadow: 2px 2px 8px rgba(0,0,0,0.1);<br/>',
  '}<br/>',
  '🖋️ 17. Text Styling<br/>',
  'h1 {<br/>',
  '  font-size: 2rem;<br/>',
  '  font-weight: bold;<br/>',
  '  text-align: center;<br/>',
  '}<br/>',
  '🖱️ 18. Hover & Active<br/>',
  'a:hover {<br/>',
  '  color: teal;<br/>',
  '}<br/>',
  'button:active {<br/>',
  '  transform: scale(0.98);<br/>',
  '}<br/>',
  '🧱 19. Flexbox - Your Layout Superpower<br/>',
  '.container {<br/>',
  '  display: flex;<br/>',
  '  justify-content: space-between;<br/>',
  '  align-items: center;<br/>',
  '}<br/>',
  'Flexbox lets you align sections like Experience, Skills, and Education side by side or stacked.<br/>',
  '🎯 20. Units - Measuring Like an Architect<br/>',
  ' `px` → Fixed<br/>',
  ' `em/rem` → Scalable<br/>',
  ' `%` → Relative<br/>',
  ' `vh/vw` → Viewport<br/>',
  '🎯 21. CSS Best Practices<br/>',
  ' Group similar styles<br/>',
  " Use variables if you're using SCSS<br/>",
  ' Mobile-first media queries<br/>',
  ' Reuse class names<br/>',
  '@media (max-width: 768px) {<br/>',
  '  .container {<br/>',
  '    flex-direction: column;<br/>',
  `  }<br/>`,
  '}<br/>',
  " "
];